# This is a config for E2B sandbox template.
# You can use template ID (klb1q1ujfuzw261h179s) or template name (vibe-nextjs-test-20) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-20") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-20") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-20')

team_id = "ff8eb560-6b89-4e83-94bd-41d194ccf181"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-20"
template_id = "klb1q1ujfuzw261h179s"
